#!/bin/bash
# PPG Python v1.1 Release Package Contents

echo "========================================"
echo "PPG Python v1.1 - Package Contents"
echo "========================================"
echo ""
echo "📦 Package: PPG_Python_v1.1.tar.gz (81 KB)"
echo ""
echo "Core Modules (4):"
echo "  ✓ ppg_pulse.py           - Pulse waveform generation"
echo "  ✓ ppg_generator.py       - Main signal generator (0.1% noise)"
echo "  ✓ ppg_artifacts.py       - Motion artifact generation"
echo "  ✓ data_loader.py         - Data loading utilities"
echo ""
echo "Main Scripts (3):"
echo "  ✓ main_ppg.py            - Main program (with FFT peak annotations)"
echo "  ✓ generate_training_data.py - Training dataset generation"
echo "  ✓ verify_artifact_params.py - NEW: Artifact parameter guide"
echo ""
echo "Examples (3):"
echo "  ✓ examples/demo_hr_resp_coupling.py"
echo "  ✓ examples/validate_ppg.py"
echo "  ✓ examples/validate_artifact_isolation.py"
echo ""
echo "Data Files (2):"
echo "  ✓ data/artifact_param.mat"
echo "  ✓ data/pulse_templates.mat"
echo ""
echo "Documentation (3):"
echo "  ✓ README.md              - UPDATED: v1.1 features"
echo "  ✓ LICENSE"
echo "  ✓ requirements.txt"
echo ""
echo "========================================"
echo "New in v1.1:"
echo "========================================"
echo "  🎨 FFT Peak Annotations (top 4 peaks)"
echo "  🔇 Noise Reduction (1% → 0.1%)"
echo "  📊 Artifact Parameter Guide"
echo "  📚 Enhanced Documentation"
echo "  🎨 Color-coded Visualizations"
echo ""
echo "========================================"
echo "Usage:"
echo "========================================"
echo "  tar -xzf PPG_Python_v1.1.tar.gz"
echo "  cd PPG_generation"
echo "  pip install -r requirements.txt"
echo "  python main_ppg.py"
echo ""
echo "✓ Ready for distribution!"
echo "========================================"
